### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by darkf** [rystills/rock-raiders-remake#4]
- What is the status of the project? What works, doesn't?
- Screenshot
- Add a license(!)

**Comment by rystills** [comment]
Thank you for your interest in the project! As of now, the only known bug is the incorrect removal of building sites from the site list prior to their completion, which is a game breaking bug and should be fixed with the next release. Should you notice anything else that appears to be incorrect behavior, please feel free to create a new issue and I'll do my best to address it. The recommendations are greatly appreciated; I will include a few screenshots and a proper license (something I should have done awhile ago) in the next release as well.

**Comment by darkf** [comment]
No worries, interesting project. A few more things I'll note:

- More descriptive README, noting that it's a 2D remake and does not require assets
- For that matter, redistributing the original assets is copyright infringement

I'd also work on refactoring rockRaiders.js to be a bit less monolithic, I think it would help a lot.

**Comment by rystills** [comment]
I will definitely be updating the README soon, but the matter of assets is a bit tricky. The original game uses 3D models, but for the sake of simplicity I decided to remake the game in 2d so that I could focus on functionality. As such, most of the graphics in this remake are not the original assets, but cropped screenshots of objects from the original game viewed from a birds eye perspective. I do not know whether or not this still warrants copyright infringement, but I would be happy to discuss this matter and any potential solutions you might be aware of.

**Comment by darkf** [comment]
Screenshotting still counts as a derivative work of the original title if the original assets are being used, unfortunately.

If you wanted to move out of the gray area I'd include a tool to extract the original textures from the game (they're in a WAD in BMP format, which browsers can load). That's higher res too. :P

If you want to discuss anything, let me know.

**Comment by rystills** [comment]
Screenshots and an appropriate open source license have been added to the project repo. The readme has been given a brief 'to do' section outlining work that needs to be done, along with links to the project forum thread and gh-pages url. Loading resources from the original game's install directory will be taken into consideration, and will be outlined in a new issue if necessary. Thanks again for the feedback :)
